name: Build and Deploy to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker auth for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (client)
        uses: docker/build-push-action@v5
        with:
          context: ./client           
          file: ./client/Dockerfile
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/client:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/client:latest \
            --platform managed \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --quiet

