name: Build and Deploy to GCR

# 이 워크플로우는 main 브랜치에 푸시할 때마다 트리거됩니다.
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud authentication
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        # credentials_json: ${{ secrets.GCP_SA_KEY }}  # 서비스 계정 키 (GitHub Secrets에 저장된 키)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./client/Dockerfile  # Dockerfile 경로
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/client:latest
        build-args: |
          VITE_API_URL=${{ secrets.VITE_API_URL }}  # API URL을 환경변수로 주입 (옵션)

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/client:latest \
          --platform managed \
          --region asia-northeast3 \
          --allow-unauthenticated
